### PR TITLE
Alphabetically order category items

### PR DESCRIPTION
**Pull request by Ogaday**

### CODE REVIEW

**Comment by MaxBenChrist** [comment]
I like the alphabetical order. Can you sort out the merge conflict?

**Comment by Ogaday** [comment]
This is actually sorted on the lowercase package names, because I think that makes more sense than sorting such as `ABC...abc...` or than `AaBbCc...` etc.

**Comment by MaxBenChrist** [comment]
Thx!

**Comment by Ogaday** [comment]
No problem, happy to contribute :)

**Pull request merged**
